# -*- encoding: utf-8 -*-

require 'rumoji/emoji'
require 'set'

module Rumoji
  class Emoji
    OBJECTS = SortedSet[
      self.new("🎍", [:bamboo], "PINE DECORATION"), # "Japanese new year's door decoration
      self.new("💝", [:gift_heart], "HEART WITH RIBBON"),
      self.new("🎎", [:dolls], "JAPANESE DOLLS"), # "Japanese Hinamatsuri or girls' doll festival"
      self.new("💝", [:gift_heart], "HEART WITH RIBBON"),
      self.new("🎒", [:school_satchel]), # "Japanese school entrance ceremony"
      self.new("🎓", [:mortar_board], "GRADUATION CAP"), # "graduation ceremony"
      self.new("🎏", [:flags], "CARP STREAMER"),
      self.new("🎆", [:fireworks]),
      self.new("🎇", [:sparkler], "FIREWORK SPARKLER"),
      self.new("🎐", [:wind_chime]),
      self.new("🎑", [:rice_scene], "MOON VIEWING CEREMONY"), # "Japanese Otsukimi harvest celebration"
      self.new("🎃", [:jack_o_lantern], "JACK-O-LANTERN"), # "Hallowe'en"
      self.new("👻", [:ghost]),
      self.new("🎅", [:santa], "FATHER CHRISTMAS"), # "Santa Claus"
      self.new("🎱", [:"8ball"]),
      self.new("⏰" , [:alarm_clock]),
      self.new("🍎", [:apple]),
      self.new("🎨", [:art]),
      self.new("🍼", [:baby_bottle]),
      self.new("🎈", [:balloon]),
      self.new("🍌", [:banana]),
      self.new("📊", [:bar_chart]),
      self.new("⚾" , [:baseball]),
      self.new("🏀", [:basketball]),
      self.new("🛀", [:bath]),
      self.new("🛁", [:bathtub]),
      self.new("🔋", [:battery]),
      self.new("🍺", [:beer]),
      self.new("🍻", [:beers]),
      self.new("🔔", [:bell]),
      self.new("🍱", [:bento]),
      self.new("🚴", [:bicyclist]),
      self.new("👙", [:bikini]),
      self.new("🎂", [:birthday]),
      self.new("🃏", [:black_joker]),
      self.new("✒" , [:black_nib]),
      self.new("📘", [:blue_book]),
      self.new("💣", [:bomb]),
      self.new("🔖", [:bookmark]),
      self.new("📑", [:bookmark_tabs]),
      self.new("📚", [:books]),
      self.new("👢", [:boot]),
      self.new("🎳", [:bowling]),
      self.new("🍞", [:bread]),
      self.new("💼", [:briefcase]),
      self.new("💡", [:bulb]),
      self.new("🍰", [:cake]),
      self.new("📆", [:calendar]),
      self.new("📲", [:calling]),
      self.new("📷", [:camera]),
      self.new("🍬", [:candy]),
      self.new("📇", [:card_index]),
      self.new("💿", [:cd]),
      self.new("📉", [:chart_with_downwards_trend]),
      self.new("📈", [:chart_with_upwards_trend]),
      self.new("🍒", [:cherries]),
      self.new("🍫", [:chocolate_bar]),
      self.new("🎄", [:christmas_tree]),
      self.new("🎬", [:clapper]),
      self.new("📋", [:clipboard]),
      self.new("📕", [:closed_book]),
      self.new("🔐", [:closed_lock_with_key]),
      self.new("🌂", [:closed_umbrella]),
      self.new("♣" , [:clubs]),
      self.new("🍸", [:cocktail]),
      self.new("☕" , [:coffee]),
      self.new("💻", [:computer]),
      self.new("🎊", [:confetti_ball]),
      self.new("🍪", [:cookie]),
      self.new("🌽", [:corn]),
      self.new("💳", [:credit_card]),
      self.new("👑", [:crown]),
      self.new("🔮", [:crystal_ball]),
      self.new("🍛", [:curry]),
      self.new("🍮", [:custard]),
      self.new("🍡", [:dango]),
      self.new("🎯", [:dart]),
      self.new("📅", [:date]),
      self.new("♦" , [:diamonds]),
      self.new("💵", [:dollar]),
      self.new("🚪", [:door]),
      self.new("🍩", [:doughnut]),
      self.new("👗", [:dress]),
      self.new("📀", [:dvd]),
      self.new("📧", [:"e-mail"]),
      self.new("🍳", [:egg]),
      self.new("🍆", [:eggplant]),
      self.new("🔌", [:electric_plug]),
      self.new("✉" , [:email, :envelope]),
      self.new("💶", [:euro]),
      self.new("👓", [:eyeglasses]),
      self.new("📠", [:fax]),
      self.new("📁", [:file_folder]),
      self.new("🍥", [:fish_cake]),
      self.new("🎣", [:fishing_pole_and_fish]),
      self.new("🔦", [:flashlight]),
      self.new("💾", [:floppy_disk]),
      self.new("🎴", [:flower_playing_cards]),
      self.new("🏈", [:football]),
      self.new("🍴", [:fork_and_knife]),
      self.new("🍤", [:fried_shrimp]),
      self.new("🍟", [:fries]),
      self.new("🎲", [:game_die]),
      self.new("💎", [:gem]),
      self.new("🎁", [:gift]),
      self.new("⛳" , [:golf]),
      self.new("🍇", [:grapes]),
      self.new("🍏", [:green_apple]),
      self.new("📗", [:green_book]),
      self.new("🎸", [:guitar]),
      self.new("🔫", [:gun]),
      self.new("🍔", [:hamburger]),
      self.new("🔨", [:hammer]),
      self.new("👜", [:handbag]),
      self.new("🎧", [:headphones]),
      self.new("♥" , [:hearts]),
      self.new("🔆", [:high_brightness]),
      self.new("👠", [:high_heel]),
      self.new("🔪", [:hocho]),
      self.new("🍯", [:honey_pot]),
      self.new("🏇", [:horse_racing]),
      self.new("⌛" , [:hourglass]),
      self.new("⏳" , [:hourglass_flowing_sand]),
      self.new("🍨", [:ice_cream]),
      self.new("🍦", [:icecream]),
      self.new("📥", [:inbox_tray]),
      self.new("📨", [:incoming_envelope]),
      self.new("📱", [:iphone]),
      self.new("👖", [:jeans]),
      self.new("🔑", [:key]),
      self.new("👘", [:kimono]),
      self.new("📒", [:ledger]),
      self.new("🍋", [:lemon]),
      self.new("💄", [:lipstick]),
      self.new("🔒", [:lock]),
      self.new("🔏", [:lock_with_ink_pen]),
      self.new("🍭", [:lollipop]),
      self.new("➿" , [:loop]),
      self.new("📢", [:loudspeaker]),
      self.new("🔅", [:low_brightness]),
      self.new("🔍", [:mag]),
      self.new("🔎", [:mag_right]),
      self.new("🀄", [:mahjong]),
      self.new("📫", [:mailbox]),
      self.new("📪", [:mailbox_closed]),
      self.new("📬", [:mailbox_with_mail]),
      self.new("📭", [:mailbox_with_no_mail]),
      self.new("👞", [:mans_shoe, :shoe]),
      self.new("🍖", [:meat_on_bone]),
      self.new("📣", [:mega]),
      self.new("🍈", [:melon]),
      self.new("📝", [:memo, :pencil]),
      self.new("🎤", [:microphone]),
      self.new("🔬", [:microscope]),
      self.new("💽", [:minidisc]),
      self.new("💸", [:money_with_wings]),
      self.new("💰", [:moneybag]),
      self.new("🚵", [:mountain_bicyclist]),
      self.new("🎥", [:movie_camera]),
      self.new("🎹", [:musical_keyboard]),
      self.new("🎼", [:musical_score]),
      self.new("🔇", [:mute]),
      self.new("📛", [:name_badge]),
      self.new("👔", [:necktie]),
      self.new("📰", [:newspaper]),
      self.new("🔕", [:no_bell]),
      self.new("📓", [:notebook]),
      self.new("📔", [:notebook_with_decorative_cover]),
      self.new("🔩", [:nut_and_bolt]),
      self.new("🍢", [:oden]),
      self.new("📂", [:open_file_folder]),
      self.new("📙", [:orange_book]),
      self.new("📤", [:outbox_tray]),
      self.new("📄", [:page_facing_up]),
      self.new("📃", [:page_with_curl]),
      self.new("📟", [:pager]),
      self.new("📎", [:paperclip]),
      self.new("🍑", [:peach]),
      self.new("🍐", [:pear]),
      self.new("✏" , [:pencil2]),
      self.new("☎" , [:phone, :telephone]),
      self.new("💊", [:pill]),
      self.new("🍍", [:pineapple]),
      self.new("🍕", [:pizza]),
      self.new("📯", [:postal_horn]),
      self.new("📮", [:postbox]),
      self.new("👝", [:pouch]),
      self.new("🍗", [:poultry_leg]),
      self.new("💷", [:pound]),
      self.new("👛", [:purse]),
      self.new("📌", [:pushpin]),
      self.new("📻", [:radio]),
      self.new("🍜", [:ramen]),
      self.new("🎀", [:ribbon]),
      self.new("🍚", [:rice]),
      self.new("🍙", [:rice_ball]),
      self.new("🍘", [:rice_cracker]),
      self.new("💍", [:ring]),
      self.new("🏉", [:rugby_football]),
      self.new("🎽", [:running_shirt_with_sash]),
      self.new("🍶", [:sake]),
      self.new("👡", [:sandal]),
      self.new("📡", [:satellite]),
      self.new("🎷", [:saxophone]),
      self.new("✂" , [:scissors]),
      self.new("📜", [:scroll]),
      self.new("💺", [:seat]),
      self.new("🍧", [:shaved_ice]),
      self.new("👕", [:shirt, :tshirt]),
      self.new("🚿", [:shower]),
      self.new("🎿", [:ski]),
      self.new("🚬", [:smoking]),
      self.new("🏂", [:snowboarder]),
      self.new("⚽" , [:soccer]),
      self.new("🔉", [:sound, :speaker_with_one_sound_wave]),
      self.new("👾", [:space_invader]),
      self.new("♠" , [:spades]),
      self.new("🍝", [:spaghetti]),
      self.new("🔊", [:speaker, :speaker_with_three_sound_waves]),
      self.new("🍲", [:stew]),
      self.new("📏", [:straight_ruler]),
      self.new("🍓", [:strawberry]),
      self.new("🏄", [:surfer]),
      self.new("🍣", [:sushi]),
      self.new("🍠", [:sweet_potato]),
      self.new("🏊", [:swimmer]),
      self.new("💉", [:syringe]),
      self.new("🎉", [:tada]),
      self.new("🎋", [:tanabata_tree]),
      self.new("🍊", [:tangerine]),
      self.new("🍵", [:tea]),
      self.new("📞", [:telephone_receiver]),
      self.new("🔭", [:telescope]),
      self.new("🎾", [:tennis]),
      self.new("🚽", [:toilet]),
      self.new("🍅", [:tomato]),
      self.new("🎩", [:tophat]),
      self.new("📐", [:triangular_ruler]),
      self.new("🏆", [:trophy]),
      self.new("🍹", [:tropical_drink]),
      self.new("🎺", [:trumpet]),
      self.new("📺", [:tv]),
      self.new("🔓", [:unlock]),
      self.new("📼", [:vhs]),
      self.new("📹", [:video_camera]),
      self.new("🎮", [:video_game]),
      self.new("🎻", [:violin]),
      self.new("⌚" , [:watch]),
      self.new("🍉", [:watermelon]),
      self.new("🍷", [:wine_glass]),
      self.new("👚", [:womans_clothes]),
      self.new("👒", [:womans_hat]),
      self.new("🔧", [:wrench]),
      self.new("💴", [:yen]),
      self.new("🛍", [:shopping_bags], "SHOPPING BAGS"),
      self.new("📿", [:prayer_beads], "PRAYER BEADS"),
      self.new("🌶", [:hot_pepper]),
      self.new("🧀", [:cheese_wedge]),
      self.new("🌭", [:hot_dog, :hotdog]),
      self.new("🌮", [:taco]),
      self.new("🌯", [:burrito]),
      self.new("🍿", [:popcorn]),
      self.new("🍾", [:bottle_popping_cork, :champagne]),
      self.new("🏺", [:amphora]),
      self.new("🕹", [:joystick]),
      self.new("🏹", [:bow_arrow, :bow_and_arrow]),
      self.new("🗡", [:dagger_knife]),
      self.new("🏳", [:waving_white_flag]),
      self.new("🏴", [:waving_black_flag]),
      self.new("🛢", [:oil_drum]),
      self.new("🛡", [:shield]),
      self.new("🗜", [:compression]),
      self.new("🛠", [:hammer_wrench, :hammer_and_wrench]),
      self.new("🗝", [:old_key]),
      self.new("🗑", [:wastebasket]),
      self.new("🗄", [:file_cabinet]),
      self.new("🗃", [:card_file_box]),
      self.new("🖇", [:linked_paperclips]),
      self.new("🗓", [:spiral_calendar, :spiral_calendar_pad]),
      self.new("🗒", [:spiral_note_pad]),
      self.new("🗂", [:card_index_dividers]),
      self.new("🖍", [:lower_left_crayon]),
      self.new("🖌", [:lower_left_paintbrush]),
      self.new("🖊", [:lower_left_ballpoint]),
      self.new("🖋", [:lower_left_fountain]),
      self.new("🗳", [:ballot_box_with_ballot]),
      self.new("🗞", [:rollet_newspaper]),
      self.new("🕯", [:candle]),
      self.new("📸", [:camera_flash, :camera_with_flash]),
      self.new("📽", [:film_projector]),
      self.new("🖲", [:trackball]),
      self.new("🖱", [:three_button_mouse]),
      self.new("🖨", [:printer]),
      self.new("💻", [:desktop_computer]),
      self.new("🎛", [:control_knobs]),
      self.new("🎚", [:level_slider]),
      self.new("🎙", [:studio_microphone]),
      self.new("🌡", [:thermometer]),
      self.new("🕰", [:mantelpiece_clock]),
      self.new("🛋", [:couch_lamp, :couch_and_lamp]),
      self.new("🛏", [:bed]),
      self.new("🛌", [:person_bed]),
      self.new("🛎", [:bellhop_bell]),
      self.new("🍽", [:fork_knife_plate, :knife_fork_plate]),
      self.new("⌨", [:keyboard], "KEYBOARD"),
      self.new("⏱", [:stopwatch], "STOPWATCH"),
      self.new("⏲", [:timer_clock], "TIMER CLOCK"),
      self.new("☠", [:skull_and_crossbones], "SKULL AND CROSSBONES"),
      self.new("⚒", [:hammer_and_pick], "HAMMER AND PICK"),
      self.new("⚔", [:crossed_swords], "CROSSED SWORDS"),
      self.new("⚖", [:scales], "SCALES"),
      self.new("⚗", [:alembic], "ALEMBIC"),
      self.new("⚙", [:gear], "GEAR"),
      self.new("⚰", [:coffin], "COFFIN"),
      self.new("⚱", [:funeral_urn], "FUNERAL URN"),
      self.new("⛏", [:pick], "PICK"),
      self.new("⛓", [:chains], "CHAINS"),
      self.new("⛱", [:umbrella_on_ground], "UMBRELLA ON GROUND"),
      self.new("🏮", [:izakaya_lantern], "IZAKAYA LANTERN"),
      self.new("📖", [:book], "OPEN BOOK"),
      self.new("📦", [:package], "PACKAGE"),
      self.new("📩", [:envelope_with_arrow], "ENVELOPE WITH DOWNWARDS ARROW ABOVE"),
      self.new("🖊", [:lower_left_ballpoint_pen], "LOWER LEFT BALLPOINT PEN"),
      self.new("🖋", [:lower_left_fountain_pen], "LOWER LEFT FOUNTAIN PEN"),
      self.new("🗞", [:rolled_up_newspaper], "ROLLED-UP NEWSPAPER"),
      self.new("🎖", [:military_medal, :medal], "MILITARY MEDAL"),
      self.new("🏅", [:sports_medal], "SPORTS MEDAL"),
      self.new("⛸", [:ice_skate], "ICE SKATE"),
    ]
  end
end
