# -*- encoding: utf-8 -*-

require 'rumoji/emoji'
require 'set'

module Rumoji
  class Emoji
    PEOPLE = SortedSet[
      self.new("😄", [:smile, :simple_smile], "SMILING FACE WITH OPEN MOUTH AND SMILING EYES"),
      self.new("😆", [:laughing], "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES"),
      self.new("😊", [:blush], "SMILING FACE WITH SMILING EYES"),
      self.new("😃", [:smiley], "SMILING FACE WITH OPEN MOUTH"),
      self.new("☺" , [:relaxed], "WHITE SMILING FACE"),
      self.new("😏", [:smirk], "SMIRKING FACE"),
      self.new("😍", [:heart_eyes], "SMILING FACE WITH HEART-SHAPED EYES"),
      self.new("😘", [:kissing_heart], "FACE THROWING KISS"),
      self.new("😚", [:kissing_closed_eyes], "KISSING FACE WITH CLOSED EYES"),
      self.new("😳", [:flushed], "FLUSHED FACE"),
      self.new("😥", [:relieved, :disappointed_relieved], "DISAPPOINTED BUT RELIEVED FACE"),
      self.new("😌", [:satisfied], "RELIEVED FACE"),
      self.new("😁", [:grin], "GRINNING FACE WITH SMILING EYES"),
      self.new("😉", [:wink], "WINKING FACE"),
      self.new("😜", [:stuck_out_tongue_winking_eye, :wink2], "FACE WITH STUCK OUT TONGUE AND WINKING EYE"), # "kidding, not serious"
      self.new("😝", [:stuck_out_tongue_closed_eyes], "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES"), # "kidding, not serious"
      self.new("😀", [:grinning], "GRINNING FACE"),
      self.new("😗", [:kissing], "KISSING FACE"),
      self.new("😙", [:kissing_smiling_eyes], "KISSING FACE WITH SMILING EYES"),
      self.new("😛", [:stuck_out_tongue], "FACE WITH STUCK-OUT TONGUE"),
      self.new("😴", [:sleeping], "SLEEPING FACE"),
      self.new("😟", [:worried], "WORRIED FACE"),
      self.new("😦", [:frowning], "FROWNING FACE WITH OPEN MOUTH"),
      self.new("😧", [:anguished], "ANGUISHED FACE"),
      self.new("😮", [:open_mouth], "FACE WITH OPEN MOUTH"),
      self.new("😬", [:grimacing], "GRIMACING FACE"),
      self.new("😕", [:confused], "CONFUSED FACE"),
      self.new("😯", [:hushed], "HUSHED FACE"),
      self.new("😑", [:expressionless], "EXPRESSIONLESS FACE"),
      self.new("😒", [:unamused], "UNAMUSED FACE"),
      self.new("😅", [:sweat_smile], "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT"),
      self.new("😓", [:sweat], "FACE WITH COLD SWEAT"),
      self.new("😩", [:weary], "WEARY FACE"),
      self.new("😔", [:pensive], "PENSIVE FACE"),
      self.new("😞", [:disappointed], "DISAPPOINTED FACE"),
      self.new("😖", [:confounded], "CONFOUNDED FACE"),
      self.new("😨", [:fearful], "FEARFUL FACE"),
      self.new("😰", [:cold_sweat], "FACE WITH OPEN MOUTH AND COLD SWEAT"),
      self.new("😣", [:persevere], "PERSEVERING FACE"),
      self.new("😢", [:cry], "CRYING FACE"),
      self.new("😭", [:sob], "LOUDLY CRYING FACE"),
      self.new("😂", [:joy], "FACE WITH TEARS OF JOY"),
      self.new("🤣", [:rofl], "ROLLING ON THE FLOOR LAUGHING"),
      self.new("😲", [:astonished], "ASTONISHED FACE"),
      self.new("😱", [:scream], "FACE SCREAMING IN FEAR"),
      self.new("😫", [:tired_face]),
      self.new("😠", [:angry], "ANGRY FACE"),
      self.new("😡", [:rage], "POUTING FACE"),
      self.new("😤", [:triumph], "FACE WITH LOOK OF TRIUMPH"),
      self.new("😪", [:sleepy], "SLEEPY FACE"),
      self.new("😋", [:yum], "FACE SAVOURING DELICIOUS FOOD"),
      self.new("😷", [:mask], "FACE WITH MEDICAL MASK"),
      self.new("😎", [:sunglasses], "SMILING FACE WITH SUNGLASSES"),
      self.new("🤡", [:clown_face], "CLOWN FACE"),
      self.new("😵", [:dizzy_face]),
      self.new("👿", [:imp]),
      self.new("😈", [:smiling_imp], "SMILING FACE WITH HORNS"),
      self.new("😐", [:neutral_face]),
      self.new("😶", [:no_mouth], "FACE WITHOUT MOUTH"),
      self.new("😇", [:innocent], "SMILING FACE WITH HALO"),
      self.new("👽", [:alien], "EXTRATERRESTRIAL ALIEN"),
      self.new("💛", [:yellow_heart]),
      self.new("💙", [:blue_heart]),
      self.new("💜", [:purple_heart]),
      self.new("❤" , [:heart], "HEAVY BLACK HEART"),
      self.new("💚", [:green_heart]),
      self.new("💔", [:broken_heart]),
      self.new("💓", [:heartbeat], "BEATING HEART"),
      self.new("💗", [:heartpulse], "GROWING HEART"),
      self.new("💕", [:two_hearts]),
      self.new("💞", [:revolving_hearts]),
      self.new("💘", [:cupid], "HEART WITH ARROW"),
      self.new("💖", [:sparkling_heart]),
      self.new("✨" , [:sparkles]),
      self.new("⭐" , [:star], "WHITE MEDIUM STAR"),
      self.new("🌟", [:star2], "GLOWING STAR"),
      self.new("🌠", [:shooting_star], "SHOOTING STAR"),
      self.new("💫", [:dizzy], "DIZZY SYMBOL"), # "circling stars, squeans"
      self.new("💥", [:boom, :collision], "COLLISION SYMBOL"),
      self.new("💢", [:anger], "ANGER SYMBOL"),
      self.new("❗" , [:exclamation], "HEAVY EXCLAMATION MARK SYMBOL"),
      self.new("❓" , [:question], "BLACK QUESTION MARK ORNAMENT"),
      self.new("❕" , [:grey_exclamation], "WHITE EXCLAMATION MARK ORNAMENT"),
      self.new("❔" , [:grey_question], "WHITE QUESTION MARK ORNAMENT"),
      self.new("💤", [:zzz], "SLEEPING SYMBOL"),
      self.new("💨", [:dash], "DASH SYMBOL"), # "running dash, briffits"
      self.new("💦", [:sweat_drops], "SPLASHING SWEAT SYMBOL"), # "plewds"
      self.new("🎶", [:notes], "MULTIPLE MUSICAL NOTES"), # "dancing notes, mood, melody"
      self.new("🎵", [:musical_note]), # "music, being in good mood"
      self.new("🔥", [:fire], "FIRE"),
      self.new("🤗", [:hugging, :hugging_face], "HUGGING FACE"),
      self.new("🤔", [:thinking, :thinking_face], "THINKING FACE"),
      self.new("🙄", [:rolling_eyes, :face_with_rolling_eyes], "FACE WITH ROLLING EYES"),
      self.new("🤐", [:zipper_mouth, :zipper_mouth_face], "ZIPPER-MOUTH FACE"),
      self.new("🤓", [:nerd, :nerd_face], "NERD FACE"),
      self.new("🙃", [:upside_down, :upside_down_face], "UPSIDE-DOWN FACE"),
      self.new("🤒", [:face_thermometer, :face_with_thermometer], "FACE WITH THERMOMETER"),
      self.new("🤕", [:head_bandage, :face_with_head_bandage], "FACE WITH HEAD-BANDAGE"),
      self.new("🤑", [:money_mouth, :money_mouth_face], "MONEY-MOUTH FACE"),
      self.new("🤖", [:robot, :robot_face], "ROBOT FACE"),
      self.new("🕵", [:sleuth, :sleuth_or_spy], "SLEUTH OR SPY"),
      self.new("🏋", [:weight_lifter], "WEIGHT LIFTER"),
      self.new("🏌", [:golfer], "GOLFER"),
      self.new("🕴", [:man_levitating, :man_in_business_suit_levitating], "MAN IN BUSINESS SUIT LEVITATING"),
      self.new("🙁", [:slightly_frowning, :slightly_frowning_face], "SLIGHTLY FROWNING FACE"),
      self.new("🙂", [:slightly_smiling, :slightly_smiling_face], "SLIGHTLY SMILING FACE"),

      # Poop
      self.new("💩", [:poop, :hankey, :shit], "PILE OF POO"), # "dog dirt"
      self.new("👍", [:thumbsup, :"+1"], "THUMBS UP SIGN"),
      self.new("👎", [:thumbsdown, :"-1"], "THUMBS DOWN SIGN"),
      self.new("👌", [:ok_hand], "OK HAND SIGN"),
      self.new("👊", [:punch, :facepunch], "FISTED HAND SIGN"), # "punch
      self.new("🤝", [:handshake], "HANDSHAKE"),
      self.new("✊" , [:fist], "RAISED FIST"),
      self.new("✌" , [:v], "VICTORY HAND"),
      self.new("👋", [:wave], "WAVING HAND SIGN"),
      self.new("✋" , [:hand], "RAISED HAND"),
      self.new("👐", [:open_hands], "OPEN HANDS SIGN"),
      self.new("☝" , [:point_up], "WHITE UP POINTING INDEX"),
      self.new("👇", [:point_down], "WHITE DOWN POINTING BACKHAND INDEX"),
      self.new("👈", [:point_left], "WHITE LEFT POINTING BACKHAND INDEX"),
      self.new("👉", [:point_right], "WHITE RIGHT POINTING BACKHAND INDEX"),
      self.new("🙌", [:raised_hands], "PERSON RAISING BOTH HANDS IN CELEBRATION"), # "banzai!"
      self.new("🙏", [:pray], "PERSON WITH FOLDED HANDS"), # "can indicate sorrow or regret; can indicate pleading"
      self.new("👆", [:point_up_2], "WHITE UP POINTING BACKHAND INDEX"),
      self.new("👏", [:clap], "CLAPPING HANDS SIGN"),
      self.new("💪", [:muscle], "FLEXED BICEPS"), # "strong, muscled"
      self.new("🚶", [:walking], "PEDESTRIAN"),
      self.new("🏃", [:runner, :running]),
      self.new("👫", [:couple], "MAN AND WOMAN HOLDING HANDS"),
      self.new("👪", [:family]),
      self.new("👬", [:two_men_holding_hands]),
      self.new("👭", [:two_women_holding_hands]),
      self.new("💃", [:dancer]),
      self.new("👯", [:dancers], "WOMAN WITH BUNNY EARS"),
      self.new("🙆", [:ok_woman], "FACE WITH OK GESTURE"),
      self.new("🙅", [:no_good], "FACE WITH NO GOOD GESTURE"),
      self.new("💁", [:information_desk_person]),
      self.new("🙋", [:raised_hand, :raising_hand], "HAPPY PERSON RAISING ONE HAND"),
      self.new("👰", [:bride_with_veil]),
      self.new("🙎", [:person_with_pouting_face]),
      self.new("🙍", [:person_frowning, :white_frowning_face]),
      self.new("🙇", [:bow], "PERSON BOWING DEEPLY"),
      self.new("💏", [:couplekiss], "KISS"), # "two people kissing"
      self.new("💑", [:couple_with_heart]),
      self.new("💆", [:massage], "FACE MASSAGE"),
      self.new("💇", [:haircut]), # "usually indicates a beauty parlor"
      self.new("💅", [:nail_care], "NAIL POLISH"), # "manicure, nail care"
      self.new("👦", [:boy]),
      self.new("👧", [:girl]),
      self.new("👩", [:woman]),
      self.new("👨", [:man]),
      self.new("👶", [:baby]),
      self.new("👵", [:older_woman]),
      self.new("👴", [:older_man]),
      self.new("👱", [:person_with_blond_hair]),
      self.new("👲", [:man_with_gua_pi_mao]),
      self.new("👳", [:man_with_turban]),
      self.new("👷", [:construction_worker]),
      self.new("👮", [:cop], "POLICE OFFICER"),
      self.new("👼", [:angel], "BABY ANGEL"),
      self.new("👸", [:princess]),
      self.new("🖕", [:middle_finger], "REVERSED HAND WITH MIDDLE FINGER EXTENDED"),
      self.new("🖖", [:vulcan_salute], "RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS"), # vulcan salute
      self.new("🤘", [:sign_horns, :the_horns], "SIGN OF THE HORNS"),
      self.new("🖐", [:fingers_splayed, :raised_hand_with_fingers_splayed], "RAISED HAND WITH FINGERS SPLAYED"),

      # Cats
      self.new("😺", [:smiley_cat], "SMILING CAT FACE WITH OPEN MOUTH"),
      self.new("😸", [:smile_cat], "GRINNING CAT FACE WITH SMILING EYES"),
      self.new("😻", [:heart_eyes_cat], "SMILING CAT FACE WITH HEART-SHAPED EYES"),
      self.new("😽", [:kissing_cat], "KISSING CAT FACE WITH CLOSED EYES"),
      self.new("😼", [:smirk_cat], "CAT FACE WITH WRY SMILE"),
      self.new("🙀", [:scream_cat], "WEARY CAT FACE"),
      self.new("😿", [:crying_cat_face], "CRYING CAT FACE"),
      self.new("😹", [:joy_cat], "CAT FACE WITH TEARS OF JOY"),
      self.new("😾", [:pouting_cat], "POUTING CAT FACE"),
      self.new("👹", [:japanese_ogre]),
      self.new("👺", [:japanese_goblin]),
      # Monkeys
      self.new("🙈", [:see_no_evil], "SEE-NO-EVIL MONKEY"),
      self.new("🙉", [:hear_no_evil], "HEAR-NO-EVIL MONKEY"),
      self.new("🙊", [:speak_no_evil], "SPEAK-NO-EVIL MONKEY"),
      self.new("💂", [:guardsman]),
      self.new("💀", [:skull]),
      self.new("👣", [:feet, :footprints], "FOOTPRINTS"),
      self.new("👄", [:lips], "MOUTH"),
      self.new("💋", [:kiss], "KISS MARK"), # "lips"
      self.new("💧", [:droplet]), # "represents a drop of sweat or drop of water"
      self.new("👂", [:ear]),
      self.new("👀", [:eyes]),
      self.new("👃", [:nose]),
      self.new("👅", [:tongue]),
      self.new("💌", [:love_letter]),
      self.new("👤", [:bust_in_silhouette]), # "guest account"
      self.new("👥", [:busts_in_silhouette]), # "accounts"
      self.new("💬", [:speech_balloon]), # "comic book conversation bubble"
      self.new("💭", [:thought_balloon]),
      self.new("🗨", [:left_speech], "LEFT SPEECH BUBBLE"),
      self.new("🗯", [:right_answer], "RIGHT ANSWER BUBBLE"),
      self.new("🕳", [:hole], "HOLE"),
      self.new("🕶", [:dark_sunglasses], "DARK SUNGLASSES"),
      self.new("🗣", [:speaking_head]),
      self.new("👁", [:eye]),
      self.new("🏻", [:type_1_2]),
      self.new("🏼", [:type_3]),
      self.new("🏽", [:type_4]),
      self.new("🏾", [:type_5]),
      self.new("🏿", [:type_6]),
      self.new("⛑", [:helmet_with_white_cross], "HELMET WITH WHITE CROSS"),
      self.new("✍", [:writing_hand], "WRITING HAND"),
      self.new("👟", [:athletic_shoe], "ATHLETIC SHOE"),
      self.new("🖖", [:vulcan_hand, :"spock-hand"], "RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS"),
      self.new("🗣", [:speaking_head_in_silhouette], "SPEAKING HEAD IN SILHOUETTE"),
      self.new("⛹", [:person_with_ball], "PERSON WITH BALL"),
      self.new("⛷", [:skier], "SKIER"),
      self.new("👨‍👨‍👦", [:"man-man-boy"], "MAN MAN BOY"),
      self.new("👨‍👨‍👦‍👦", [:"man-man-boy-boy"], "MAN MAN BOY BOY"),
      self.new("👨‍👨‍👧‍👦", [:"man-man-girl-boy"], "MAN MAN GIRL BOY"),
      self.new(" ", [:"man-man-girl-girl"], "MAN MAN GIRL GIRL"),
      self.new("👨‍👨‍👧", [:"man-man-girl"], "MAN MAN GIRL"),
      self.new("👨‍👩‍👧‍👧", [:"man-woman-girl-girl"], "MAN WOMAN GIRL GIRL"),
      self.new("👨‍👩‍👦‍👦", [:"man-woman-boy-boy"], "MAN WOMAN BOY BOY"),
      self.new("👨‍👩‍👧", [:"man-woman-girl"], "MAN WOMAN GIRL"),
      self.new("👨‍👩‍👧‍👦", [:"man-woman-girl-boy"], "MAN WOMAN GIRL BOY"),
      self.new("👩‍👩‍👦", [:"woman-woman-boy"], "WOMAN WOMAN BOY"),
      self.new("👩‍👩‍👦‍👦", [:"woman-woman-boy-boy"], "WOMAN WOMAN BOY BOY"),
      self.new("👩‍👩‍👧", [:"woman-woman-girl"], "WOMAN WOMAN GIRL"),
      self.new("👩‍👩‍👧‍👦", [:"woman-woman-girl-boy"], "WOMAN WOMAN GIRL BOY"),
      self.new("👩‍👩‍👧‍👧", [:"woman-woman-girl-girl"], "WOMAN WOMAN GIRL GIRL"),
      self.new("👩‍❤️‍💋‍👨", [:"woman-kiss-man"], "WOMAN KISS MAN"), # ZWJ version of U+1F48F ("couple kiss")
      self.new("👩‍❤️‍👨", [:"woman-heart-man"], "WOMAN HEART MAN"), # ZWJ version of U+1F491 ("couple with heart")
      self.new("👨‍👩‍👦", [:"man-woman-boy"], "MAN WOMAN BOY BOY"), # ZWJ version of U+1F46A ("family")
      self.new("👨‍❤️‍👨", [:"man-heart-man"], "MAN HEART MAN"),
      self.new("👨‍❤️‍💋‍👨", [:"man-kiss-man"], "MAN KISS MAN"),
      self.new("👩‍❤️‍👩", [:"woman-heart-woman"], "WOMAN HEART WOMAN"),
      self.new("👩‍❤️‍💋‍👩", [:"woman-kiss-woman"], "WOMAN KISS WOMAN"),
    ]
  end
end
