# -*- encoding: utf-8 -*-

require 'rumoji/emoji'
require 'set'

module Rumoji
  class Emoji
    PLACES = SortedSet[
      self.new("🚡", [:aerial_tramway]),
      self.new("✈" , [:airplane]),
      self.new("🚑", [:ambulance]),
      self.new("⚓" , [:anchor]),
      self.new("🚛", [:articulated_lorry]),
      self.new("🏧", [:atm]),
      self.new("🏦", [:bank]),
      self.new("💈", [:barber]),
      self.new("🔰", [:beginner]),
      self.new("🚲", [:bike]),
      self.new("🚙", [:blue_car]),
      self.new("⛵" , [:boat, :sailboat]),
      self.new("🌉", [:bridge_at_night]),
      self.new("🚅", [:bullettrain_front]),
      self.new("🚄", [:bullettrain_side]),
      self.new("🚌", [:bus]),
      self.new("🚏", [:busstop]),
      self.new("🚗", [:car, :red_car]),
      self.new("🎠", [:carousel_horse]),
      self.new("🏁", [:checkered_flag]),
      self.new("⛪" , [:church]),
      self.new("🎪", [:circus_tent]),
      self.new("🌇", [:city_sunrise]),
      self.new("🌆", [:city_sunset]),
      self.new("🚧", [:construction]),
      self.new("🏪", [:convenience_store]),
      self.new("🎌", [:crossed_flags]),
      self.new("🏬", [:department_store]),
      self.new("🏰", [:european_castle]),
      self.new("🏤", [:european_post_office]),
      self.new("🏭", [:factory]),
      self.new("🎡", [:ferris_wheel]),
      self.new("🚒", [:fire_engine]),
      self.new("⛲" , [:fountain]),
      self.new("⛽" , [:fuelpump]),
      self.new("🚁", [:helicopter]),
      self.new("🏥", [:hospital]),
      self.new("🏨", [:hotel]),
      self.new("♨" , [:hotsprings]),
      self.new("🏠", [:house]),
      self.new("🏡", [:house_with_garden]),
      self.new("🗾", [:japan]),
      self.new("🏯", [:japanese_castle]),
      self.new("🚈", [:light_rail]),
      self.new("🏩", [:love_hotel]),
      self.new("🚐", [:minibus]),
      self.new("🚝", [:monorail]),
      self.new("🗻", [:mount_fuji]),
      self.new("🚠", [:mountain_cableway]),
      self.new("🚞", [:mountain_railway]),
      self.new("🗿", [:moyai]),
      self.new("🏢", [:office]),
      self.new("🚘", [:oncoming_automobile]),
      self.new("🚍", [:oncoming_bus]),
      self.new("🚔", [:oncoming_police_car]),
      self.new("🚖", [:oncoming_taxi]),
      self.new("🎭", [:performing_arts]),
      self.new("🚓", [:police_car]),
      self.new("🏣", [:post_office]),
      self.new("🚃", [:railway_car, :train]),
      self.new("🌈", [:rainbow]),
      self.new("🚀", [:rocket]),
      self.new("🎢", [:roller_coaster]),
      self.new("🚨", [:rotating_light]),
      self.new("📍", [:round_pushpin]),
      self.new("🚣", [:rowboat]),
      self.new("🏫", [:school]),
      self.new("🚢", [:ship]),
      self.new("🎰", [:slot_machine]),
      self.new("🚤", [:speedboat]),
      self.new("🌃", [:stars, :night_with_stars]),
      self.new("🚉", [:station]),
      self.new("🗽", [:statue_of_liberty]),
      self.new("🚂", [:steam_locomotive]),
      self.new("🌅", [:sunrise]),
      self.new("🌄", [:sunrise_over_mountains]),
      self.new("🚟", [:suspension_railway]),
      self.new("🚕", [:taxi]),
      self.new("⛺" , [:tent]),
      self.new("🎫", [:ticket]),
      self.new("🗼", [:tokyo_tower]),
      self.new("🚜", [:tractor]),
      self.new("🚥", [:traffic_light]),
      self.new("🚆", [:train2]),
      self.new("🚊", [:tram]),
      self.new("🚩", [:triangular_flag_on_post]),
      self.new("🚎", [:trolleybus]),
      self.new("🚚", [:truck]),
      self.new("🚦", [:vertical_traffic_light]),
      self.new("⚠" , [:warning]),
      self.new("💒", [:wedding]),
      self.new("🕋", [:kaaba]),
      self.new("🕌", [:mosque]),
      self.new("🕍", [:synagogue]),
      self.new("🏎", [:racing_car]),
      self.new("🏍", [:racing_motorcycle]),
      self.new("🏏", [:cricket_bat_ball, :cricket_bat_and_ball]),
      self.new("🏐", [:volleyball]),
      self.new("🏑", [:field_hockey_stick, :field_hockey_stick_and_ball]),
      self.new("🏒", [:ice_hockey_stick, :ice_hockey_stick_and_puck]),
      self.new("🏓", [:table_tennis_paddle, :table_tennis_paddle_and_ball]),
      self.new("🏸", [:badminton_racquet, :badminton_racquet_and_shuttlecock]),
      self.new("🏷", [:label]),
      self.new("🎟", [:admission_tickets]),
      self.new("🎞", [:film_frames]),
      self.new("🎗", [:reminder_ribbon]),
      self.new("🛰", [:satellite]),
      self.new("🛬", [:airplane_landing, :airplane_arriving]),
      self.new("🛫", [:airplane_departing, :airplane_departure]),
      self.new("🛩", [:small_airplane]),
      self.new("🛥", [:motor_boat]),
      self.new("🛳", [:passenger_ship]),
      self.new("🛤", [:railway_track]),
      self.new("🛣", [:motorway]),
      self.new("🖼", [:frame_with_picture]),
      self.new("🏚", [:derelict_house_building]),
      self.new("🏙", [:cityscape]),
      self.new("🏘", [:house_buildings]),
      self.new("🏗", [:building_construction]),
      self.new("🏛", [:classical_building]),
      self.new("🏟", [:stadium]),
      self.new("🏞", [:national_park]),
      self.new("🏝", [:desert_island]),
      self.new("🏜", [:desert]),
      self.new("🏖", [:beach_umbrella, :beach_with_umbrella]),
      self.new("🏕", [:camping]),
      self.new("🏔", [:snow_capped_mountain, :mountain]),
      self.new("🗺", [:world_map]),
      self.new("⛩", [:shinto_shrine], "SHINTO SHRINE"),
      self.new("⛴", [:ferry], "FERRY"),

      # Regional Indicator Symbols
      self.new("🇦🇨", [:"flag-ac"], "REGIONAL INDICATOR SYMBOL LETTERS AC"),
      self.new("🇦🇩", [:"flag-ad"], "REGIONAL INDICATOR SYMBOL LETTERS AD"),
      self.new("🇦🇪", [:"flag-ae"], "REGIONAL INDICATOR SYMBOL LETTERS AE"),
      self.new("🇦🇫", [:"flag-af"], "REGIONAL INDICATOR SYMBOL LETTERS AF"),
      self.new("🇦🇬", [:"flag-ag"], "REGIONAL INDICATOR SYMBOL LETTERS AG"),
      self.new("🇦🇮", [:"flag-ai"], "REGIONAL INDICATOR SYMBOL LETTERS AI"),
      self.new("🇦🇱", [:"flag-al"], "REGIONAL INDICATOR SYMBOL LETTERS AL"),
      self.new("🇦🇲", [:"flag-am"], "REGIONAL INDICATOR SYMBOL LETTERS AM"),
      self.new("🇦🇴", [:"flag-ao"], "REGIONAL INDICATOR SYMBOL LETTERS AO"),
      self.new("🇦🇶", [:"flag-aq"], "REGIONAL INDICATOR SYMBOL LETTERS AQ"),
      self.new("🇦🇷", [:"flag-ar"], "REGIONAL INDICATOR SYMBOL LETTERS AR"),
      self.new("🇦🇸", [:"flag-as"], "REGIONAL INDICATOR SYMBOL LETTERS AS"),
      self.new("🇦🇹", [:"flag-at"], "REGIONAL INDICATOR SYMBOL LETTERS AT"),
      self.new("🇦🇺", [:"flag-au"], "REGIONAL INDICATOR SYMBOL LETTERS AU"),
      self.new("🇦🇼", [:"flag-aw"], "REGIONAL INDICATOR SYMBOL LETTERS AW"),
      self.new("🇦🇽", [:"flag-ax"], "REGIONAL INDICATOR SYMBOL LETTERS AX"),
      self.new("🇦🇿", [:"flag-az"], "REGIONAL INDICATOR SYMBOL LETTERS AZ"),
      self.new("🇧🇦", [:"flag-ba"], "REGIONAL INDICATOR SYMBOL LETTERS BA"),
      self.new("🇧🇧", [:"flag-bb"], "REGIONAL INDICATOR SYMBOL LETTERS BB"),
      self.new("🇧🇩", [:"flag-bd"], "REGIONAL INDICATOR SYMBOL LETTERS BD"),
      self.new("🇧🇪", [:"flag-be"], "REGIONAL INDICATOR SYMBOL LETTERS BE"),
      self.new("🇧🇫", [:"flag-bf"], "REGIONAL INDICATOR SYMBOL LETTERS BF"),
      self.new("🇧🇬", [:"flag-bg"], "REGIONAL INDICATOR SYMBOL LETTERS BG"),
      self.new("🇧🇭", [:"flag-bh"], "REGIONAL INDICATOR SYMBOL LETTERS BH"),
      self.new("🇧🇮", [:"flag-bi"], "REGIONAL INDICATOR SYMBOL LETTERS BI"),
      self.new("🇧🇯", [:"flag-bj"], "REGIONAL INDICATOR SYMBOL LETTERS BJ"),
      self.new("🇧🇱", [:"flag-bl"], "REGIONAL INDICATOR SYMBOL LETTERS BL"),
      self.new("🇧🇲", [:"flag-bm"], "REGIONAL INDICATOR SYMBOL LETTERS BM"),
      self.new("🇧🇳", [:"flag-bn"], "REGIONAL INDICATOR SYMBOL LETTERS BN"),
      self.new("🇧🇴", [:"flag-bo"], "REGIONAL INDICATOR SYMBOL LETTERS BO"),
      self.new("🇧🇶", [:"flag-bq"], "REGIONAL INDICATOR SYMBOL LETTERS BQ"),
      self.new("🇧🇷", [:"flag-br"], "REGIONAL INDICATOR SYMBOL LETTERS BR"),
      self.new("🇧🇸", [:"flag-bs"], "REGIONAL INDICATOR SYMBOL LETTERS BS"),
      self.new("🇧🇹", [:"flag-bt"], "REGIONAL INDICATOR SYMBOL LETTERS BT"),
      self.new("🇧🇻", [:"flag-bv"], "REGIONAL INDICATOR SYMBOL LETTERS BV"),
      self.new("🇧🇼", [:"flag-bw"], "REGIONAL INDICATOR SYMBOL LETTERS BW"),
      self.new("🇧🇾", [:"flag-by"], "REGIONAL INDICATOR SYMBOL LETTERS BY"),
      self.new("🇧🇿", [:"flag-bz"], "REGIONAL INDICATOR SYMBOL LETTERS BZ"),
      self.new("🇨🇦", [:"flag-ca"], "REGIONAL INDICATOR SYMBOL LETTERS CA"),
      self.new("🇨🇨", [:"flag-cc"], "REGIONAL INDICATOR SYMBOL LETTERS CC"),
      self.new("🇨🇩", [:"flag-cd"], "REGIONAL INDICATOR SYMBOL LETTERS CD"),
      self.new("🇨🇫", [:"flag-cf"], "REGIONAL INDICATOR SYMBOL LETTERS CF"),
      self.new("🇨🇬", [:"flag-cg"], "REGIONAL INDICATOR SYMBOL LETTERS CG"),
      self.new("🇨🇭", [:"flag-ch"], "REGIONAL INDICATOR SYMBOL LETTERS CH"),
      self.new("🇨🇮", [:"flag-ci"], "REGIONAL INDICATOR SYMBOL LETTERS CI"),
      self.new("🇨🇰", [:"flag-ck"], "REGIONAL INDICATOR SYMBOL LETTERS CK"),
      self.new("🇨🇱", [:"flag-cl"], "REGIONAL INDICATOR SYMBOL LETTERS CL"),
      self.new("🇨🇲", [:"flag-cm"], "REGIONAL INDICATOR SYMBOL LETTERS CM"),
      self.new("🇨🇳", [:"flag-cn", :cn], "REGIONAL INDICATOR SYMBOL LETTERS CN"),
      self.new("🇨🇴", [:"flag-co"], "REGIONAL INDICATOR SYMBOL LETTERS CO"),
      self.new("🇨🇵", [:"flag-cp"], "REGIONAL INDICATOR SYMBOL LETTERS CP"),
      self.new("🇨🇷", [:"flag-cr"], "REGIONAL INDICATOR SYMBOL LETTERS CR"),
      self.new("🇨🇺", [:"flag-cu"], "REGIONAL INDICATOR SYMBOL LETTERS CU"),
      self.new("🇨🇻", [:"flag-cv"], "REGIONAL INDICATOR SYMBOL LETTERS CV"),
      self.new("🇨🇼", [:"flag-cw"], "REGIONAL INDICATOR SYMBOL LETTERS CW"),
      self.new("🇨🇽", [:"flag-cx"], "REGIONAL INDICATOR SYMBOL LETTERS CX"),
      self.new("🇨🇾", [:"flag-cy"], "REGIONAL INDICATOR SYMBOL LETTERS CY"),
      self.new("🇨🇿", [:"flag-cz"], "REGIONAL INDICATOR SYMBOL LETTERS CZ"),
      self.new("🇩🇪", [:"flag-de", :de], "REGIONAL INDICATOR SYMBOL LETTERS DE"),
      self.new("🇩🇬", [:"flag-dg"], "REGIONAL INDICATOR SYMBOL LETTERS DG"),
      self.new("🇩🇯", [:"flag-dj"], "REGIONAL INDICATOR SYMBOL LETTERS DJ"),
      self.new("🇩🇰", [:"flag-dk"], "REGIONAL INDICATOR SYMBOL LETTERS DK"),
      self.new("🇩🇲", [:"flag-dm"], "REGIONAL INDICATOR SYMBOL LETTERS DM"),
      self.new("🇩🇴", [:"flag-do"], "REGIONAL INDICATOR SYMBOL LETTERS DO"),
      self.new("🇩🇿", [:"flag-dz"], "REGIONAL INDICATOR SYMBOL LETTERS DZ"),
      self.new("🇪🇦", [:"flag-ea"], "REGIONAL INDICATOR SYMBOL LETTERS EA"),
      self.new("🇪🇨", [:"flag-ec"], "REGIONAL INDICATOR SYMBOL LETTERS EC"),
      self.new("🇪🇪", [:"flag-ee"], "REGIONAL INDICATOR SYMBOL LETTERS EE"),
      self.new("🇪🇬", [:"flag-eg"], "REGIONAL INDICATOR SYMBOL LETTERS EG"),
      self.new("🇪🇭", [:"flag-eh"], "REGIONAL INDICATOR SYMBOL LETTERS EH"),
      self.new("🇪🇷", [:"flag-er"], "REGIONAL INDICATOR SYMBOL LETTERS ER"),
      self.new("🇪🇸", [:"flag-es", :es], "REGIONAL INDICATOR SYMBOL LETTERS ES"),
      self.new("🇪🇹", [:"flag-et"], "REGIONAL INDICATOR SYMBOL LETTERS ET"),
      self.new("🇪🇺", [:"flag-eu"], "REGIONAL INDICATOR SYMBOL LETTERS EU"),
      self.new("🇫🇮", [:"flag-fi"], "REGIONAL INDICATOR SYMBOL LETTERS FI"),
      self.new("🇫🇯", [:"flag-fj"], "REGIONAL INDICATOR SYMBOL LETTERS FJ"),
      self.new("🇫🇰", [:"flag-fk"], "REGIONAL INDICATOR SYMBOL LETTERS FK"),
      self.new("🇫🇲", [:"flag-fm"], "REGIONAL INDICATOR SYMBOL LETTERS FM"),
      self.new("🇫🇴", [:"flag-fo"], "REGIONAL INDICATOR SYMBOL LETTERS FO"),
      self.new("🇫🇷", [:"flag-fr", :fr], "REGIONAL INDICATOR SYMBOL LETTERS FR"),
      self.new("🇬🇦", [:"flag-ga"], "REGIONAL INDICATOR SYMBOL LETTERS GA"),
      self.new("🇬🇧", [:"flag-gb", :gb, :uk], "REGIONAL INDICATOR SYMBOL LETTERS GB"),
      self.new("🇬🇩", [:"flag-gd"], "REGIONAL INDICATOR SYMBOL LETTERS GD"),
      self.new("🇬🇪", [:"flag-ge"], "REGIONAL INDICATOR SYMBOL LETTERS GE"),
      self.new("🇬🇫", [:"flag-gf"], "REGIONAL INDICATOR SYMBOL LETTERS GF"),
      self.new("🇬🇬", [:"flag-gg"], "REGIONAL INDICATOR SYMBOL LETTERS GG"),
      self.new("🇬🇭", [:"flag-gh"], "REGIONAL INDICATOR SYMBOL LETTERS GH"),
      self.new("🇬🇮", [:"flag-gi"], "REGIONAL INDICATOR SYMBOL LETTERS GI"),
      self.new("🇬🇱", [:"flag-gl"], "REGIONAL INDICATOR SYMBOL LETTERS GL"),
      self.new("🇬🇲", [:"flag-gm"], "REGIONAL INDICATOR SYMBOL LETTERS GM"),
      self.new("🇬🇳", [:"flag-gn"], "REGIONAL INDICATOR SYMBOL LETTERS GN"),
      self.new("🇬🇵", [:"flag-gp"], "REGIONAL INDICATOR SYMBOL LETTERS GP"),
      self.new("🇬🇶", [:"flag-gq"], "REGIONAL INDICATOR SYMBOL LETTERS GQ"),
      self.new("🇬🇷", [:"flag-gr"], "REGIONAL INDICATOR SYMBOL LETTERS GR"),
      self.new("🇬🇸", [:"flag-gs"], "REGIONAL INDICATOR SYMBOL LETTERS GS"),
      self.new("🇬🇹", [:"flag-gt"], "REGIONAL INDICATOR SYMBOL LETTERS GT"),
      self.new("🇬🇺", [:"flag-gu"], "REGIONAL INDICATOR SYMBOL LETTERS GU"),
      self.new("🇬🇼", [:"flag-gw"], "REGIONAL INDICATOR SYMBOL LETTERS GW"),
      self.new("🇬🇾", [:"flag-gy"], "REGIONAL INDICATOR SYMBOL LETTERS GY"),
      self.new("🇭🇰", [:"flag-hk"], "REGIONAL INDICATOR SYMBOL LETTERS HK"),
      self.new("🇭🇲", [:"flag-hm"], "REGIONAL INDICATOR SYMBOL LETTERS HM"),
      self.new("🇭🇳", [:"flag-hn"], "REGIONAL INDICATOR SYMBOL LETTERS HN"),
      self.new("🇭🇷", [:"flag-hr"], "REGIONAL INDICATOR SYMBOL LETTERS HR"),
      self.new("🇭🇹", [:"flag-ht"], "REGIONAL INDICATOR SYMBOL LETTERS HT"),
      self.new("🇭🇺", [:"flag-hu"], "REGIONAL INDICATOR SYMBOL LETTERS HU"),
      self.new("🇮🇨", [:"flag-ic"], "REGIONAL INDICATOR SYMBOL LETTERS IC"),
      self.new("🇮🇩", [:"flag-id"], "REGIONAL INDICATOR SYMBOL LETTERS ID"),
      self.new("🇮🇪", [:"flag-ie"], "REGIONAL INDICATOR SYMBOL LETTERS IE"),
      self.new("🇮🇱", [:"flag-il"], "REGIONAL INDICATOR SYMBOL LETTERS IL"),
      self.new("🇮🇲", [:"flag-im"], "REGIONAL INDICATOR SYMBOL LETTERS IM"),
      self.new("🇮🇳", [:"flag-in"], "REGIONAL INDICATOR SYMBOL LETTERS IN"),
      self.new("🇮🇴", [:"flag-io"], "REGIONAL INDICATOR SYMBOL LETTERS IO"),
      self.new("🇮🇶", [:"flag-iq"], "REGIONAL INDICATOR SYMBOL LETTERS IQ"),
      self.new("🇮🇷", [:"flag-ir"], "REGIONAL INDICATOR SYMBOL LETTERS IR"),
      self.new("🇮🇸", [:"flag-is"], "REGIONAL INDICATOR SYMBOL LETTERS IS"),
      self.new("🇮🇹", [:"flag-it", :it], "REGIONAL INDICATOR SYMBOL LETTERS IT"),
      self.new("🇯🇪", [:"flag-je"], "REGIONAL INDICATOR SYMBOL LETTERS JE"),
      self.new("🇯🇲", [:"flag-jm"], "REGIONAL INDICATOR SYMBOL LETTERS JM"),
      self.new("🇯🇴", [:"flag-jo"], "REGIONAL INDICATOR SYMBOL LETTERS JO"),
      self.new("🇯🇵", [:"flag-jp", :jp], "REGIONAL INDICATOR SYMBOL LETTERS JP"),
      self.new("🇰🇪", [:"flag-ke"], "REGIONAL INDICATOR SYMBOL LETTERS KE"),
      self.new("🇰🇬", [:"flag-kg"], "REGIONAL INDICATOR SYMBOL LETTERS KG"),
      self.new("🇰🇭", [:"flag-kh"], "REGIONAL INDICATOR SYMBOL LETTERS KH"),
      self.new("🇰🇮", [:"flag-ki"], "REGIONAL INDICATOR SYMBOL LETTERS KI"),
      self.new("🇰🇲", [:"flag-km"], "REGIONAL INDICATOR SYMBOL LETTERS KM"),
      self.new("🇰🇳", [:"flag-kn"], "REGIONAL INDICATOR SYMBOL LETTERS KN"),
      self.new("🇰🇵", [:"flag-kp"], "REGIONAL INDICATOR SYMBOL LETTERS KP"),
      self.new("🇰🇷", [:"flag-kr", :kr], "REGIONAL INDICATOR SYMBOL LETTERS KR"),
      self.new("🇰🇼", [:"flag-kw"], "REGIONAL INDICATOR SYMBOL LETTERS KW"),
      self.new("🇰🇾", [:"flag-ky"], "REGIONAL INDICATOR SYMBOL LETTERS KY"),
      self.new("🇰🇿", [:"flag-kz"], "REGIONAL INDICATOR SYMBOL LETTERS KZ"),
      self.new("🇱🇦", [:"flag-la"], "REGIONAL INDICATOR SYMBOL LETTERS LA"),
      self.new("🇱🇧", [:"flag-lb"], "REGIONAL INDICATOR SYMBOL LETTERS LB"),
      self.new("🇱🇨", [:"flag-lc"], "REGIONAL INDICATOR SYMBOL LETTERS LC"),
      self.new("🇱🇮", [:"flag-li"], "REGIONAL INDICATOR SYMBOL LETTERS LI"),
      self.new("🇱🇰", [:"flag-lk"], "REGIONAL INDICATOR SYMBOL LETTERS LK"),
      self.new("🇱🇷", [:"flag-lr"], "REGIONAL INDICATOR SYMBOL LETTERS LR"),
      self.new("🇱🇸", [:"flag-ls"], "REGIONAL INDICATOR SYMBOL LETTERS LS"),
      self.new("🇱🇹", [:"flag-lt"], "REGIONAL INDICATOR SYMBOL LETTERS LT"),
      self.new("🇱🇺", [:"flag-lu"], "REGIONAL INDICATOR SYMBOL LETTERS LU"),
      self.new("🇱🇻", [:"flag-lv"], "REGIONAL INDICATOR SYMBOL LETTERS LV"),
      self.new("🇱🇾", [:"flag-ly"], "REGIONAL INDICATOR SYMBOL LETTERS LY"),
      self.new("🇲🇦", [:"flag-ma"], "REGIONAL INDICATOR SYMBOL LETTERS MA"),
      self.new("🇲🇨", [:"flag-mc"], "REGIONAL INDICATOR SYMBOL LETTERS MC"),
      self.new("🇲🇩", [:"flag-md"], "REGIONAL INDICATOR SYMBOL LETTERS MD"),
      self.new("🇲🇪", [:"flag-me"], "REGIONAL INDICATOR SYMBOL LETTERS ME"),
      self.new("🇲🇫", [:"flag-mf"], "REGIONAL INDICATOR SYMBOL LETTERS MF"),
      self.new("🇲🇬", [:"flag-mg"], "REGIONAL INDICATOR SYMBOL LETTERS MG"),
      self.new("🇲🇭", [:"flag-mh"], "REGIONAL INDICATOR SYMBOL LETTERS MH"),
      self.new("🇲🇰", [:"flag-mk"], "REGIONAL INDICATOR SYMBOL LETTERS MK"),
      self.new("🇲🇱", [:"flag-ml"], "REGIONAL INDICATOR SYMBOL LETTERS ML"),
      self.new("🇲🇲", [:"flag-mm"], "REGIONAL INDICATOR SYMBOL LETTERS MM"),
      self.new("🇲🇳", [:"flag-mn"], "REGIONAL INDICATOR SYMBOL LETTERS MN"),
      self.new("🇲🇴", [:"flag-mo"], "REGIONAL INDICATOR SYMBOL LETTERS MO"),
      self.new("🇲🇵", [:"flag-mp"], "REGIONAL INDICATOR SYMBOL LETTERS MP"),
      self.new("🇲🇶", [:"flag-mq"], "REGIONAL INDICATOR SYMBOL LETTERS MQ"),
      self.new("🇲🇷", [:"flag-mr"], "REGIONAL INDICATOR SYMBOL LETTERS MR"),
      self.new("🇲🇸", [:"flag-ms"], "REGIONAL INDICATOR SYMBOL LETTERS MS"),
      self.new("🇲🇹", [:"flag-mt"], "REGIONAL INDICATOR SYMBOL LETTERS MT"),
      self.new("🇲🇺", [:"flag-mu"], "REGIONAL INDICATOR SYMBOL LETTERS MU"),
      self.new("🇲🇻", [:"flag-mv"], "REGIONAL INDICATOR SYMBOL LETTERS MV"),
      self.new("🇲🇼", [:"flag-mw"], "REGIONAL INDICATOR SYMBOL LETTERS MW"),
      self.new("🇲🇽", [:"flag-mx"], "REGIONAL INDICATOR SYMBOL LETTERS MX"),
      self.new("🇲🇾", [:"flag-my"], "REGIONAL INDICATOR SYMBOL LETTERS MY"),
      self.new("🇲🇿", [:"flag-mz"], "REGIONAL INDICATOR SYMBOL LETTERS MZ"),
      self.new("🇳🇦", [:"flag-na"], "REGIONAL INDICATOR SYMBOL LETTERS NA"),
      self.new("🇳🇨", [:"flag-nc"], "REGIONAL INDICATOR SYMBOL LETTERS NC"),
      self.new("🇳🇪", [:"flag-ne"], "REGIONAL INDICATOR SYMBOL LETTERS NE"),
      self.new("🇳🇫", [:"flag-nf"], "REGIONAL INDICATOR SYMBOL LETTERS NF"),
      self.new("🇳🇬", [:"flag-ng"], "REGIONAL INDICATOR SYMBOL LETTERS NG"),
      self.new("🇳🇮", [:"flag-ni"], "REGIONAL INDICATOR SYMBOL LETTERS NI"),
      self.new("🇳🇱", [:"flag-nl"], "REGIONAL INDICATOR SYMBOL LETTERS NL"),
      self.new("🇳🇴", [:"flag-no"], "REGIONAL INDICATOR SYMBOL LETTERS NO"),
      self.new("🇳🇵", [:"flag-np"], "REGIONAL INDICATOR SYMBOL LETTERS NP"),
      self.new("🇳🇷", [:"flag-nr"], "REGIONAL INDICATOR SYMBOL LETTERS NR"),
      self.new("🇳🇺", [:"flag-nu"], "REGIONAL INDICATOR SYMBOL LETTERS NU"),
      self.new("🇳🇿", [:"flag-nz"], "REGIONAL INDICATOR SYMBOL LETTERS NZ"),
      self.new("🇴🇲", [:"flag-om"], "REGIONAL INDICATOR SYMBOL LETTERS OM"),
      self.new("🇵🇦", [:"flag-pa"], "REGIONAL INDICATOR SYMBOL LETTERS PA"),
      self.new("🇵🇪", [:"flag-pe"], "REGIONAL INDICATOR SYMBOL LETTERS PE"),
      self.new("🇵🇫", [:"flag-pf"], "REGIONAL INDICATOR SYMBOL LETTERS PF"),
      self.new("🇵🇬", [:"flag-pg"], "REGIONAL INDICATOR SYMBOL LETTERS PG"),
      self.new("🇵🇭", [:"flag-ph"], "REGIONAL INDICATOR SYMBOL LETTERS PH"),
      self.new("🇵🇰", [:"flag-pk"], "REGIONAL INDICATOR SYMBOL LETTERS PK"),
      self.new("🇵🇱", [:"flag-pl"], "REGIONAL INDICATOR SYMBOL LETTERS PL"),
      self.new("🇵🇲", [:"flag-pm"], "REGIONAL INDICATOR SYMBOL LETTERS PM"),
      self.new("🇵🇳", [:"flag-pn"], "REGIONAL INDICATOR SYMBOL LETTERS PN"),
      self.new("🇵🇷", [:"flag-pr"], "REGIONAL INDICATOR SYMBOL LETTERS PR"),
      self.new("🇵🇸", [:"flag-ps"], "REGIONAL INDICATOR SYMBOL LETTERS PS"),
      self.new("🇵🇹", [:"flag-pt"], "REGIONAL INDICATOR SYMBOL LETTERS PT"),
      self.new("🇵🇼", [:"flag-pw"], "REGIONAL INDICATOR SYMBOL LETTERS PW"),
      self.new("🇵🇾", [:"flag-py"], "REGIONAL INDICATOR SYMBOL LETTERS PY"),
      self.new("🇶🇦", [:"flag-qa"], "REGIONAL INDICATOR SYMBOL LETTERS QA"),
      self.new("🇷🇪", [:"flag-re"], "REGIONAL INDICATOR SYMBOL LETTERS RE"),
      self.new("🇷🇴", [:"flag-ro"], "REGIONAL INDICATOR SYMBOL LETTERS RO"),
      self.new("🇷🇸", [:"flag-rs"], "REGIONAL INDICATOR SYMBOL LETTERS RS"),
      self.new("🇷🇺", [:"flag-ru", :ru], "REGIONAL INDICATOR SYMBOL LETTERS RU"),
      self.new("🇷🇼", [:"flag-rw"], "REGIONAL INDICATOR SYMBOL LETTERS RW"),
      self.new("🇸🇦", [:"flag-sa"], "REGIONAL INDICATOR SYMBOL LETTERS SA"),
      self.new("🇸🇧", [:"flag-sb"], "REGIONAL INDICATOR SYMBOL LETTERS SB"),
      self.new("🇸🇨", [:"flag-sc"], "REGIONAL INDICATOR SYMBOL LETTERS SC"),
      self.new("🇸🇩", [:"flag-sd"], "REGIONAL INDICATOR SYMBOL LETTERS SD"),
      self.new("🇸🇪", [:"flag-se"], "REGIONAL INDICATOR SYMBOL LETTERS SE"),
      self.new("🇸🇬", [:"flag-sg"], "REGIONAL INDICATOR SYMBOL LETTERS SG"),
      self.new("🇸🇭", [:"flag-sh"], "REGIONAL INDICATOR SYMBOL LETTERS SH"),
      self.new("🇸🇮", [:"flag-si"], "REGIONAL INDICATOR SYMBOL LETTERS SI"),
      self.new("🇸🇯", [:"flag-sj"], "REGIONAL INDICATOR SYMBOL LETTERS SJ"),
      self.new("🇸🇰", [:"flag-sk"], "REGIONAL INDICATOR SYMBOL LETTERS SK"),
      self.new("🇸🇱", [:"flag-sl"], "REGIONAL INDICATOR SYMBOL LETTERS SL"),
      self.new("🇸🇲", [:"flag-sm"], "REGIONAL INDICATOR SYMBOL LETTERS SM"),
      self.new("🇸🇳", [:"flag-sn"], "REGIONAL INDICATOR SYMBOL LETTERS SN"),
      self.new("🇸🇴", [:"flag-so"], "REGIONAL INDICATOR SYMBOL LETTERS SO"),
      self.new("🇸🇷", [:"flag-sr"], "REGIONAL INDICATOR SYMBOL LETTERS SR"),
      self.new("🇸🇸", [:"flag-ss"], "REGIONAL INDICATOR SYMBOL LETTERS SS"),
      self.new("🇸🇹", [:"flag-st"], "REGIONAL INDICATOR SYMBOL LETTERS ST"),
      self.new("🇸🇻", [:"flag-sv"], "REGIONAL INDICATOR SYMBOL LETTERS SV"),
      self.new("🇸🇽", [:"flag-sx"], "REGIONAL INDICATOR SYMBOL LETTERS SX"),
      self.new("🇸🇾", [:"flag-sy"], "REGIONAL INDICATOR SYMBOL LETTERS SY"),
      self.new("🇸🇿", [:"flag-sz"], "REGIONAL INDICATOR SYMBOL LETTERS SZ"),
      self.new("🇹🇦", [:"flag-ta"], "REGIONAL INDICATOR SYMBOL LETTERS TA"),
      self.new("🇹🇨", [:"flag-tc"], "REGIONAL INDICATOR SYMBOL LETTERS TC"),
      self.new("🇹🇩", [:"flag-td"], "REGIONAL INDICATOR SYMBOL LETTERS TD"),
      self.new("🇹🇫", [:"flag-tf"], "REGIONAL INDICATOR SYMBOL LETTERS TF"),
      self.new("🇹🇬", [:"flag-tg"], "REGIONAL INDICATOR SYMBOL LETTERS TG"),
      self.new("🇹🇭", [:"flag-th"], "REGIONAL INDICATOR SYMBOL LETTERS TH"),
      self.new("🇹🇯", [:"flag-tj"], "REGIONAL INDICATOR SYMBOL LETTERS TJ"),
      self.new("🇹🇰", [:"flag-tk"], "REGIONAL INDICATOR SYMBOL LETTERS TK"),
      self.new("🇹🇱", [:"flag-tl"], "REGIONAL INDICATOR SYMBOL LETTERS TL"),
      self.new("🇹🇲", [:"flag-tm"], "REGIONAL INDICATOR SYMBOL LETTERS TM"),
      self.new("🇹🇳", [:"flag-tn"], "REGIONAL INDICATOR SYMBOL LETTERS TN"),
      self.new("🇹🇴", [:"flag-to"], "REGIONAL INDICATOR SYMBOL LETTERS TO"),
      self.new("🇹🇷", [:"flag-tr"], "REGIONAL INDICATOR SYMBOL LETTERS TR"),
      self.new("🇹🇹", [:"flag-tt"], "REGIONAL INDICATOR SYMBOL LETTERS TT"),
      self.new("🇹🇻", [:"flag-tv"], "REGIONAL INDICATOR SYMBOL LETTERS TV"),
      self.new("🇹🇼", [:"flag-tw"], "REGIONAL INDICATOR SYMBOL LETTERS TW"),
      self.new("🇹🇿", [:"flag-tz"], "REGIONAL INDICATOR SYMBOL LETTERS TZ"),
      self.new("🇺🇦", [:"flag-ua"], "REGIONAL INDICATOR SYMBOL LETTERS UA"),
      self.new("🇺🇬", [:"flag-ug"], "REGIONAL INDICATOR SYMBOL LETTERS UG"),
      self.new("🇺🇲", [:"flag-um"], "REGIONAL INDICATOR SYMBOL LETTERS UM"),
      self.new("🇺🇸", [:"flag-us", :us], "REGIONAL INDICATOR SYMBOL LETTERS US"),
      self.new("🇺🇾", [:"flag-uy"], "REGIONAL INDICATOR SYMBOL LETTERS UY"),
      self.new("🇺🇿", [:"flag-uz"], "REGIONAL INDICATOR SYMBOL LETTERS UZ"),
      self.new("🇻🇦", [:"flag-va"], "REGIONAL INDICATOR SYMBOL LETTERS VA"),
      self.new("🇻🇨", [:"flag-vc"], "REGIONAL INDICATOR SYMBOL LETTERS VC"),
      self.new("🇻🇪", [:"flag-ve"], "REGIONAL INDICATOR SYMBOL LETTERS VE"),
      self.new("🇻🇬", [:"flag-vg"], "REGIONAL INDICATOR SYMBOL LETTERS VG"),
      self.new("🇻🇮", [:"flag-vi"], "REGIONAL INDICATOR SYMBOL LETTERS VI"),
      self.new("🇻🇳", [:"flag-vn"], "REGIONAL INDICATOR SYMBOL LETTERS VN"),
      self.new("🇻🇺", [:"flag-vu"], "REGIONAL INDICATOR SYMBOL LETTERS VU"),
      self.new("🇼🇫", [:"flag-wf"], "REGIONAL INDICATOR SYMBOL LETTERS WF"),
      self.new("🇼🇸", [:"flag-ws"], "REGIONAL INDICATOR SYMBOL LETTERS WS"),
      self.new("🇽🇰", [:"flag-xk"], "REGIONAL INDICATOR SYMBOL LETTERS XK"),
      self.new("🇾🇪", [:"flag-ye"], "REGIONAL INDICATOR SYMBOL LETTERS YE"),
      self.new("🇾🇹", [:"flag-yt"], "REGIONAL INDICATOR SYMBOL LETTERS YT"),
      self.new("🇿🇦", [:"flag-za"], "REGIONAL INDICATOR SYMBOL LETTERS ZA"),
      self.new("🇿🇲", [:"flag-zm"], "REGIONAL INDICATOR SYMBOL LETTERS ZM"),
      self.new("🇿🇼", [:"flag-zw"], "REGIONAL INDICATOR SYMBOL LETTERS ZW")
    ]
  end
end
