# -*- encoding: utf-8 -*-

require 'rumoji/emoji'
require 'set'

module Rumoji
  class Emoji
    SYMBOLS = SortedSet[
      self.new("💯", [:"100"]),
      self.new("🔢", [:"1234"]),
      self.new("🅰", [:a]),
      self.new("🆎", [:ab]),
      self.new("🔤", [:abc]),
      self.new("🔡", [:abcd]),
      self.new("🉑", [:accept]),
      self.new("♒" , [:aquarius]),
      self.new("♈" , [:aries]),
      self.new("◀" , [:arrow_backward]),
      self.new("⏬" , [:arrow_double_down]),
      self.new("⏫" , [:arrow_double_up]),
      self.new("⬇" , [:arrow_down]),
      self.new("🔽", [:arrow_down_small]),
      self.new("▶" , [:arrow_forward]),
      self.new("⤵" , [:arrow_heading_down]),
      self.new("⤴" , [:arrow_heading_up]),
      self.new("⬅" , [:arrow_left]),
      self.new("↙" , [:arrow_lower_left]),
      self.new("↘" , [:arrow_lower_right]),
      self.new("➡" , [:arrow_right]),
      self.new("↪" , [:arrow_right_hook]),
      self.new("⬆" , [:arrow_up]),
      self.new("↕" , [:arrow_up_down]),
      self.new("🔼", [:arrow_up_small]),
      self.new("↖" , [:arrow_upper_left]),
      self.new("↗" , [:arrow_upper_right]),
      self.new("🔃", [:arrows_clockwise]),
      self.new("🔄", [:arrows_counterclockwise]),
      self.new("🅱", [:b]),
      self.new("🚼", [:baby_symbol]),
      self.new("🛄", [:baggage_claim]),
      self.new("☑" , [:ballot_box_with_check]),
      self.new("‼" , [:bangbang]),
      self.new("⚫" , [:black_circle]),
      self.new("🔲", [:black_square_button]),
      self.new("♋" , [:cancer]),
      self.new("🔠", [:capital_abcd]),
      self.new("♑" , [:capricorn]),
      self.new("💹", [:chart]),
      self.new("🚸", [:children_crossing]),
      self.new("🎦", [:cinema]),
      self.new("🆑", [:cl]),
      self.new("🕐", [:clock1]),
      self.new("🕙", [:clock10]),
      self.new("🕥", [:clock1030]),
      self.new("🕚", [:clock11]),
      self.new("🕦", [:clock1130]),
      self.new("🕛", [:clock12]),
      self.new("🕧", [:clock1230]),
      self.new("🕜", [:clock130]),
      self.new("🕑", [:clock2]),
      self.new("🕝", [:clock230]),
      self.new("🕒", [:clock3]),
      self.new("🕞", [:clock330]),
      self.new("🕓", [:clock4]),
      self.new("🕟", [:clock430]),
      self.new("🕔", [:clock5]),
      self.new("🕠", [:clock530]),
      self.new("🕕", [:clock6]),
      self.new("🕡", [:clock630]),
      self.new("🕖", [:clock7]),
      self.new("🕢", [:clock730]),
      self.new("🕗", [:clock8]),
      self.new("🕣", [:clock830]),
      self.new("🕘", [:clock9]),
      self.new("🕤", [:clock930]),
      self.new("㊗" , [:congratulations]),
      self.new("🆒", [:cool]),
      self.new("©" , [:copyright]),
      self.new("➰" , [:curly_loop]),
      self.new("💱", [:currency_exchange]),
      self.new("🛃", [:customs]),
      self.new("💠", [:diamond_shape_with_a_dot_inside]),
      self.new("🚯", [:do_not_litter]),
      self.new("8️⃣" , [:eight]),
      self.new("✴" , [:eight_pointed_black_star]),
      self.new("✳" , [:eight_spoked_asterisk]),
      self.new("🔚", [:end]),
      self.new("⏩" , [:fast_forward]),
      self.new("5️⃣" , [:five]),
      self.new("4️⃣" , [:four]),
      self.new("🆓", [:free]),
      self.new("♊" , [:gemini]),
      self.new("#️⃣" , [:hash]),
      self.new("💟", [:heart_decoration]),
      self.new("✔" , [:heavy_check_mark]),
      self.new("➗" , [:heavy_division_sign]),
      self.new("💲", [:heavy_dollar_sign]),
      self.new("➖" , [:heavy_minus_sign]),
      self.new("✖" , [:heavy_multiplication_x]),
      self.new("➕" , [:heavy_plus_sign]),
      self.new("🆔", [:id]),
      self.new("🉐", [:ideograph_advantage]),
      self.new("ℹ" , [:information_source]),
      self.new("⁉" , [:interrobang]),
      self.new("🔟", [:keycap_ten]),
      self.new("🈁", [:koko]),
      self.new("🔵", [:large_blue_circle]),
      self.new("🔷", [:large_blue_diamond]),
      self.new("🔶", [:large_orange_diamond]),
      self.new("🛅", [:left_luggage]),
      self.new("↔" , [:left_right_arrow]),
      self.new("↩" , [:leftwards_arrow_with_hook]),
      self.new("♌" , [:leo]),
      self.new("♎" , [:libra]),
      self.new("🔗", [:link]),
      self.new("Ⓜ" , [:m]),
      self.new("🚹", [:mens]),
      self.new("🚇", [:metro]),
      self.new("📴", [:mobile_phone_off]),
      self.new("❎" , [:negative_squared_cross_mark]),
      self.new("🆕", [:new]),
      self.new("🆖", [:ng]),
      self.new("9️⃣" , [:nine]),
      self.new("🚳", [:no_bicycles]),
      self.new("⛔" , [:no_entry]),
      self.new("🚫", [:no_entry_sign]),
      self.new("📵", [:no_mobile_phones]),
      self.new("🚷", [:no_pedestrians]),
      self.new("🚭", [:no_smoking]),
      self.new("🚱", [:"non-potable_water"]),
      self.new("⭕" , [:o]),
      self.new("🅾", [:o2]),
      self.new("🆗", [:ok]),
      self.new("🔛", [:on]),
      self.new("1️⃣" , [:one]),
      self.new("⛎" , [:ophiuchus]),
      self.new("🅿", [:parking]),
      self.new("〽" , [:part_alternation_mark]),
      self.new("🛂", [:passport_control]),
      self.new("♓" , [:pisces]),
      self.new("🚰", [:potable_water]),
      self.new("🚮", [:put_litter_in_its_place]),
      self.new("🔘", [:radio_button]),
      self.new("♻" , [:recycle]),
      self.new("🔴", [:red_circle]),
      self.new("®" , [:registered]),
      self.new("🔁", [:repeat]),
      self.new("🔂", [:repeat_one]),
      self.new("🚻", [:restroom]),
      self.new("⏪" , [:rewind]),
      self.new("🈂", [:sa]),
      self.new("♐" , [:sagittarius]),
      self.new("♏" , [:scorpius]),
      self.new("㊙" , [:secret]),
      self.new("7️⃣" , [:seven]),
      self.new("📶", [:signal_strength]),
      self.new("6️⃣" , [:six]),
      self.new("🔯", [:six_pointed_star]),
      self.new("🔹", [:small_blue_diamond]),
      self.new("🔸", [:small_orange_diamond]),
      self.new("🔺", [:small_red_triangle]),
      self.new("🔻", [:small_red_triangle_down]),
      self.new("🔜", [:soon]),
      self.new("🆘", [:sos]),
      self.new("🔣", [:symbols]),
      self.new("♉" , [:taurus]),
      self.new("3️⃣" , [:three]),
      self.new("™" , [:tm]),
      self.new("🔝", [:top]),
      self.new("🔱", [:trident]),
      self.new("🔀", [:twisted_rightwards_arrows]),
      self.new("2️⃣" , [:two]),
      self.new("🈹", [:u5272]),
      self.new("🈴", [:u5408]),
      self.new("🈺", [:u55b6]),
      self.new("🈯", [:u6307]),
      self.new("🈷", [:u6708]),
      self.new("🈶", [:u6709]),
      self.new("🈵", [:u6e80]),
      self.new("🈚", [:u7121]),
      self.new("🈸", [:u7533]),
      self.new("🈲", [:u7981]),
      self.new("🈳", [:u7a7a]),
      self.new("🔞", [:underage]),
      self.new("🆙", [:up]),
      self.new("📳", [:vibration_mode]),
      self.new("♍" , [:virgo]),
      self.new("🆚", [:vs]),
      self.new("〰" , [:wavy_dash]),
      self.new("🚾", [:wc]),
      self.new("♿" , [:wheelchair]),
      self.new("✅" , [:white_check_mark]),
      self.new("⚪" , [:white_circle]),
      self.new("💮", [:white_flower]),
      self.new("🔳", [:white_square_button]),
      self.new("🚺", [:womens]),
      self.new("❌" , [:x]),
      self.new("0️⃣" , [:zero]),
      self.new("🏺", [:black_circle_record]),
      self.new("🏹", [:black_square_stop]),
      self.new("⏸", [:double_vertical_bar]),
      self.new("🕉", [:om, :om_symbol]),
      self.new("🛐", [:place_worship]),
      self.new("🕎", [:menorah, :menorah_with_nine_branches]),
      self.new("⏭", [:black_right_pointing_double_triangle_with_vertical_bar], "BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR"),
      self.new("⏮", [:black_left_pointing_double_triangle_with_vertical_bar], "BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR"),
      self.new("⏯", [:black_right_pointing_triangle_with_double_vertical_bar], "BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR"),
      self.new("⏹", [:black_square_for_stop], "BLACK SQUARE FOR STOP"),
      self.new("⏺", [:black_circle_for_record], "BLACK CIRCLE FOR RECORD"),
      self.new("▪", [:black_small_square], "BLACK SMALL SQUARE"),
      self.new("▫", [:white_small_square], "WHITE SMALL SQUARE"),
      self.new("◻", [:white_medium_square], "WHITE MEDIUM SQUARE"),
      self.new("◼", [:black_medium_square], "BLACK MEDIUM SQUARE"),
      self.new("◽", [:white_medium_small_square], "WHITE MEDIUM SMALL SQUARE"),
      self.new("◾", [:black_medium_small_square], "BLACK MEDIUM SMALL SQUARE"),
      self.new("☢", [:radioactive_sign], "RADIOACTIVE SIGN"),
      self.new("☣", [:biohazard_sign], "BIOHAZARD SIGN"),
      self.new("☦", [:orthodox_cross], "ORTHODOX CROSS"),
      self.new("☪", [:star_and_crescent], "STAR AND CRESCENT"),
      self.new("☮", [:peace_symbol], "PEACE SYMBOL"),
      self.new("☯", [:yin_yang], "YIN YANG"),
      self.new("☸", [:wheel_of_dharma], "WHEEL OF DHARMA"),
      self.new("⚛", [:atom_symbol], "ATOM SYMBOL"),
      self.new("⚜", [:fleur_de_lis], "FLEUR-DE-LIS"),
      self.new("✝", [:latin_cross], "LATIN CROSS"),
      self.new("✡", [:star_of_david], "STAR OF DAVID"),
      self.new("❇", [:sparkle], "SPARKLE"),
      self.new("❣", [:heavy_heart_exclamation_mark_ornament], "HEAVY HEART EXCLAMATION MARK ORNAMENT"),
      self.new("⬛", [:black_large_square], "BLACK LARGE SQUARE"),
      self.new("⬜", [:white_large_square], "WHITE LARGE SQUARE"),
      self.new("🔊", [:loud_sound], "SPEAKER WITH THREE SOUND WAVES"),
      self.new("🔙", [:back], "BACK WITH LEFTWARDS ARROW ABOVE"),
      self.new("🗯", [:right_anger_bubble], "RIGHT ANGER BUBBLE"),
      self.new("🛐", [:place_of_worship], "PLACE OF WORSHIP"),
      self.new("🛌", [:sleeping_accommodation], "SLEEPING ACCOMMODATION"),
    ]
  end
end
